# Generated by Django 5.0.4 on 2024-08-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_items_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
